.TH "GUI" 3 "Sat May 20 2023" "Task_Scheduler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainApp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_columns\fP (data)"
.br
.ti -1c
.RI "def \fBget_rows\fP (data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBBTN_SIZE\fP = (\&.14, \&.1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def GUI\&.get_columns ( data)"

.SS "def GUI\&.get_rows ( data)"

.SH "Variable Documentation"
.PP 
.SS "tuple GUI\&.BTN_SIZE = (\&.14, \&.1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Task_Scheduler from the source code\&.
