.TH "GUI.py" 3 "Sat May 20 2023" "Task_Scheduler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGUI\&.MainApp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGUI\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBGUI\&.get_columns\fP (data)"
.br
.ti -1c
.RI "def \fBGUI\&.get_rows\fP (data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBGUI\&.BTN_SIZE\fP = (\&.14, \&.1)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task_Scheduler from the source code\&.
