.TH "GUI.MainApp" 3 "Sat May 20 2023" "Task_Scheduler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI.MainApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits MDApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdelete_table\fP (self, screen)"
.br
.ti -1c
.RI "def \fBbuild\fP (self)"
.br
.ti -1c
.RI "def \fBchecked\fP (self, instance_table, current_row)"
.br
.ti -1c
.RI "def \fBrow_checked\fP (self, instance_table, instance_row)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def GUI\&.MainApp\&.build ( self)"

.SS "def GUI\&.MainApp\&.checked ( self,  instance_table,  current_row)"

.SS "def GUI\&.MainApp\&.delete_table ( self,  screen)"

.SS "def GUI\&.MainApp\&.row_checked ( self,  instance_table,  instance_row)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Task_Scheduler from the source code\&.
