.TH "test" 3 "Sat May 20 2023" "Task_Scheduler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_rows\fP (data)"
.br
.ti -1c
.RI "def \fBget_columns\fP (data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBres2\fP = []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def test\&.get_columns ( data)"

.SS "def test\&.get_rows ( data)"

.SH "Variable Documentation"
.PP 
.SS "list test\&.res2 = []"

.SH "Author"
.PP 
Generated automatically by Doxygen for Task_Scheduler from the source code\&.
